services:
  postgres:
    image: postgres:16
    container_name: nestjs-ecommerce-postgres
    restart: always

    environment:
      POSTGRES_USER: hassan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce

    ports:
      - "5432:5432"

    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
